# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:
- job: One
  pool:
    vmImage: 'ubuntu-latest'
  steps: 
  - task: PowerShell@2
    name: "psJob"
    inputs:
      targetType: 'inline'
      script: |
        $version = "aaaaaaaa2"
        Write-Host "##vso[task.setvariable variable=SurveyJSVersion;isOutput=true]$version"

- job: Two
  dependsOn: One
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    SurveyJSVersion: $[ dependencies.One.outputs['psJob.SurveyJSVersion'] ]
  steps:
  - powershell: |
      $version = "$(SurveyJSVersion)"
      Write-Host "$env:SurveyJSVersion"
      Write-Host "$version"
    displayName: 'see SurveyJSVersion'
