# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: One
  pool:
    vmImage: 'ubuntu-latest'
  steps: 
  - task: PowerShell@2
    name: "varContainer"
    inputs:
      targetType: 'inline'
      script: |
        $version = "aaaaaaaa2"
        Write-Host "##vso[task.setvariable variable=SurveyJSVersion;isOutput=true]$version"

- job: Between
  dependsOn: One
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    SurveyJSVersion: $[ dependencies.One.outputs['varContainer.SurveyJSVersion'] ]
  steps:
  - powershell: |
      Write-Host "##vso[task.setvariable variable=SurveyJSVersion;isOutput=true]$version"

- job: Two
  dependsOn: Between
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    SurveyJSVersion: $[ dependencies.One.outputs['varContainer.SurveyJSVersion'] ]
  steps:
  - powershell: |
      $version = "$(SurveyJSVersion)"
      Write-Host "2 $version"
      echo "3 variable value is $(SurveyJSVersion)"
      echo "4 variable value is $version"
    displayName: 'see SurveyJSVersion'